INSERT INTO events (dream_id, description, image, dream_index) 
VALUES
(1, 'In the future, Lunar Haven thrived, uniting scientists globally in lunar exploration. Solar panels powered facilities, fostering camaraderie in this international hub. The crater home shielded residents from lunar challenges.', 'https://th.bing.com/th/id/OIG.U8okKF8kOOAgCk3FQlV9?pid=ImgGn', 0 ),
(1,  'Known as "Lunar Haven," this outpost on the moons surface was a testament to human ingenuity. Its inhabitants, scientists, and pioneers from various nations, collaborated in the quest to unravel lunar mysteries. Hydroponic gardens and leisure areas thrived within its pressurized walls.', 'https://th.bing.com/th/id/OIG.U8okKF8kOOAgCk3FQlV9?pid=ImgGn', 1 ),
(1,   'Each day, Lunar Havens observatory offered breathtaking views of Earth hanging in the sky above. The moon had become a pivotal stepping stone, inspiring future generations to reach further into the cosmos. Lunar Haven stood as a beacon of hope and human curiosity.' , 'https://th.bing.com/th/id/OIG.U8okKF8kOOAgCk3FQlV9?pid=ImgGn', 2 ),
(2,   'Jasper, a rainforest monkey, stood out, despising bananas amid a troop that adored them. His treetop haven forbade the yellow fruit. Jaspers eccentricity amused others, turning his banana-free life into a jungle legend.',  'https://www.bing.com/th?id=OUG.63A6AC5B2E7DA6922C70AD49E5755695&w=236&c=11&rs=1&qlt=90&bgcl=ececec&o=6&pid=PersonalBing&p=0', 0 ),
(2,   'Deep in Eldorias heart, Jaspers comical attempts to avoid bananas became the talk of the jungle. The other monkeys swung gracefully, peeling and munching on bananas, while Jasper scowled at the mere sight. Tales of Jaspers banana aversion echoed through the rainforest, making him the eccentric outlier in a world where bananas were ubiquitous.',  'https://www.bing.com/th?id=OUG.63A6AC5B2E7DA6922C70AD49E5755695&w=236&c=11&rs=1&qlt=90&bgcl=ececec&o=6&pid=PersonalBing&p=0', 1 ),
(2,   'The jungle resounded with the curious tales of Jaspers banana aversion, and the other monkeys often found themselves entertained by his comical attempts to avoid the ubiquitous fruit. As the arboreal community thrived on the banana bounty, Jasper remained the eccentric outlier, living a banana-free existence in a world where the mere thought of bananas made him cringe.',  'https://www.bing.com/th?id=OUG.63A6AC5B2E7DA6922C70AD49E5755695&w=236&c=11&rs=1&qlt=90&bgcl=ececec&o=6&pid=PersonalBing&p=0', 2 ),
(3,   'Princess Seraphina sought an expanded castle symbolizing unity and diplomacy. Collaborating with skilled artisans, she envisioned a stronghold fostering alliances. The expanded castle became a hub where cultures intertwined, bringing prosperity to Eldoria.',  'https://th.bing.com/th/id/OIG.VDTvT.SjLWRcz9rNgsWr?pid=ImgGn', 0 ),
(3,   'Princess Seraphina, known for her wisdom and compassion, envisioned towering spires and sprawling gardens for the expanded castle. Plans unfolded, and the construction became a symbol of unity. The castle stood proudly, echoing with laughter and shared dreams, ushering in a new era of prosperity and understanding.',  'https://th.bing.com/th/id/OIG.VDTvT.SjLWRcz9rNgsWr?pid=ImgGn', 1 ),
(3,   'In the enchanting realm of Eldoria, Princess Seraphina found herself yearning for more than the confines of her majestic castle could offer. The expanded castle, now a testament to Seraphinas vision and the collaborative spirit of Eldoria, stood proudly against the horizon. Its walls echoed with laughter and shared dreams, becoming a hub where cultures intertwined and alliances flourished, bringing a new era of prosperity and understanding to the once-isolated kingdom.',  'https://th.bing.com/th/id/OIG.VDTvT.SjLWRcz9rNgsWr?pid=ImgGn', 2 ),
(4,   'Alex Sterling, a determined racecar driver, aimed for victory in the Grand Prix of Velocity Peak. His precision on the track and strategic maneuvers navigated the challenging course. Amid fierce competition, he surged ahead, claiming triumph at the finish line.',  'https://th.bing.com/th/id/OIG.GWXzyBy4bwU.Es.2KLQP?pid=ImgGn', 0 ),
(4,   'In the world of high-speed adrenaline and roaring engines, Alex Sterling geared up for the most challenging race of his career. The Grand Prix of Velocity Peak was renowned for its treacherous twists and turns, pushing drivers and their machines to the limits. Each turn, each acceleration, and every strategic move brought him one step closer to the coveted checkered flag.',  'https://th.bing.com/th/id/OIG.GWXzyBy4bwU.Es.2KLQP?pid=ImgGn', 1 ),
(4,   'The competition was fierce, with rival drivers hot on his tail, attempting to outmaneuver and outpace him. Yet, Alexs focus remained unwavering. He expertly calculated every move, seizing opportunities to overtake competitors and defend his position. As he crossed the finish line, the crowd erupted in cheers, and Alex Sterling stood triumphant, a testament to skill, strategy, and an unrelenting pursuit of the need for speed.',  'https://th.bing.com/th/id/OIG.GWXzyBy4bwU.Es.2KLQP?pid=ImgGn', 2 )






 
 
 
